services:
  ml-platform:
    image: ${DOCKER_REPOSITORY}/${IMAGE_NAME}:${VERSION}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - username=${USERNAME}
        - commonlib=${COMMON_LIB_NAME}
    ports:
      - "8888:8888"
    volumes:
      # persist code local code repos and
      - local_dev:/home/${USERNAME}/dev
      # Store ssh key here so it persists
      - ssh_keys:/home/${USERNAME}/.ssh
    env_file:
      - .env

volumes:
  local_dev:
    external: True
  ssh_keys:
    external: True
